# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appkey.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appkey.proto',
  package='appkey',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61ppkey.proto\x12\x06\x61ppkey\"B\n\x08Location\x12\x1b\n\x02s3\x18\x01 \x01(\x0b\x32\r.appkey.S3RefH\x00\x12\r\n\x03url\x18\x02 \x01(\tH\x00\x42\n\n\x08location\"}\n\x03\x41pp\x12\n\n\x02id\x18\x01 \x01(\x04\x12#\n\x04keys\x18\x02 \x03(\x0b\x32\x15.appkey.App.KeysEntry\x1a\x45\n\tKeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.appkey.AppKeyIndexEntry:\x02\x38\x01\"\x1b\n\rAppIndexEntry\x12\n\n\x02id\x18\x01 \x01(\x04\"\x82\x01\n\x08\x41ppIndex\x12/\n\x08\x61pp_refs\x18\x01 \x03(\x0b\x32\x1d.appkey.AppIndex.AppRefsEntry\x1a\x45\n\x0c\x41ppRefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.appkey.AppIndexEntry:\x02\x38\x01\"4\n\x05S3Ref\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\"h\n\nAppKeyMeta\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\x12\x0b\n\x03\x61pp\x18\x02 \x01(\x04\x12\x10\n\x08\x64isabled\x18\x03 \x01(\x08\x12\x12\n\nnot_before\x18\x04 \x01(\t\x12\x12\n\nnoat_after\x18\x05 \x01(\t\"7\n\x06\x41ppKey\x12 \n\x04meta\x18\x01 \x01(\x0b\x32\x12.appkey.AppKeyMeta\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"4\n\x10\x41ppKeyIndexEntry\x12 \n\x04meta\x18\x01 \x01(\x0b\x32\x12.appkey.AppKeyMeta\"7\n\x13\x41ppKeyManagerConfig\x12 \n\x06\x64\x62_loc\x18\x01 \x01(\x0b\x32\x10.appkey.Location\"F\n\x05Links\x12\x11\n\tapp_index\x18\x01 \x01(\t\x12\x0b\n\x03\x61pp\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x10\n\x08key_meta\x18\x04 \x01(\t\"r\n\x11\x41ppKeySignRequest\x12\x0b\n\x03\x61pp\x18\x01 \x01(\x04\x12\x16\n\x0eprotected_data\x18\x02 \x01(\x0c\x12\x11\n\talgorithm\x18\x03 \x01(\t\x12\x15\n\x0b\x66ingerprint\x18\x04 \x01(\tH\x00\x42\x0e\n\x0ckey_selector\"U\n\x10\x41ppKeySignedData\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x11\n\talgorithm\x18\x02 \x01(\t\x12\x1b\n\x13signing_fingerprint\x18\x03 \x01(\tB\nZ\x08\x61ppkeypbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='appkey.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s3', full_name='appkey.Location.s3', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='appkey.Location.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='location', full_name='appkey.Location.location',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=24,
  serialized_end=90,
)


_APP_KEYSENTRY = _descriptor.Descriptor(
  name='KeysEntry',
  full_name='appkey.App.KeysEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='appkey.App.KeysEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='appkey.App.KeysEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=217,
)

_APP = _descriptor.Descriptor(
  name='App',
  full_name='appkey.App',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='appkey.App.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='appkey.App.keys', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_APP_KEYSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=217,
)


_APPINDEXENTRY = _descriptor.Descriptor(
  name='AppIndexEntry',
  full_name='appkey.AppIndexEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='appkey.AppIndexEntry.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=246,
)


_APPINDEX_APPREFSENTRY = _descriptor.Descriptor(
  name='AppRefsEntry',
  full_name='appkey.AppIndex.AppRefsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='appkey.AppIndex.AppRefsEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='appkey.AppIndex.AppRefsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=379,
)

_APPINDEX = _descriptor.Descriptor(
  name='AppIndex',
  full_name='appkey.AppIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_refs', full_name='appkey.AppIndex.app_refs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_APPINDEX_APPREFSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=379,
)


_S3REF = _descriptor.Descriptor(
  name='S3Ref',
  full_name='appkey.S3Ref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket', full_name='appkey.S3Ref.bucket', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='appkey.S3Ref.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='appkey.S3Ref.region', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=433,
)


_APPKEYMETA = _descriptor.Descriptor(
  name='AppKeyMeta',
  full_name='appkey.AppKeyMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='appkey.AppKeyMeta.fingerprint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='appkey.AppKeyMeta.app', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disabled', full_name='appkey.AppKeyMeta.disabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='not_before', full_name='appkey.AppKeyMeta.not_before', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noat_after', full_name='appkey.AppKeyMeta.noat_after', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=539,
)


_APPKEY = _descriptor.Descriptor(
  name='AppKey',
  full_name='appkey.AppKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='appkey.AppKey.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='appkey.AppKey.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=596,
)


_APPKEYINDEXENTRY = _descriptor.Descriptor(
  name='AppKeyIndexEntry',
  full_name='appkey.AppKeyIndexEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='appkey.AppKeyIndexEntry.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=650,
)


_APPKEYMANAGERCONFIG = _descriptor.Descriptor(
  name='AppKeyManagerConfig',
  full_name='appkey.AppKeyManagerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_loc', full_name='appkey.AppKeyManagerConfig.db_loc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=707,
)


_LINKS = _descriptor.Descriptor(
  name='Links',
  full_name='appkey.Links',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_index', full_name='appkey.Links.app_index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='appkey.Links.app', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='appkey.Links.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key_meta', full_name='appkey.Links.key_meta', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=779,
)


_APPKEYSIGNREQUEST = _descriptor.Descriptor(
  name='AppKeySignRequest',
  full_name='appkey.AppKeySignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='appkey.AppKeySignRequest.app', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protected_data', full_name='appkey.AppKeySignRequest.protected_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='appkey.AppKeySignRequest.algorithm', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='appkey.AppKeySignRequest.fingerprint', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key_selector', full_name='appkey.AppKeySignRequest.key_selector',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=781,
  serialized_end=895,
)


_APPKEYSIGNEDDATA = _descriptor.Descriptor(
  name='AppKeySignedData',
  full_name='appkey.AppKeySignedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='appkey.AppKeySignedData.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='appkey.AppKeySignedData.algorithm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signing_fingerprint', full_name='appkey.AppKeySignedData.signing_fingerprint', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=897,
  serialized_end=982,
)

_LOCATION.fields_by_name['s3'].message_type = _S3REF
_LOCATION.oneofs_by_name['location'].fields.append(
  _LOCATION.fields_by_name['s3'])
_LOCATION.fields_by_name['s3'].containing_oneof = _LOCATION.oneofs_by_name['location']
_LOCATION.oneofs_by_name['location'].fields.append(
  _LOCATION.fields_by_name['url'])
_LOCATION.fields_by_name['url'].containing_oneof = _LOCATION.oneofs_by_name['location']
_APP_KEYSENTRY.fields_by_name['value'].message_type = _APPKEYINDEXENTRY
_APP_KEYSENTRY.containing_type = _APP
_APP.fields_by_name['keys'].message_type = _APP_KEYSENTRY
_APPINDEX_APPREFSENTRY.fields_by_name['value'].message_type = _APPINDEXENTRY
_APPINDEX_APPREFSENTRY.containing_type = _APPINDEX
_APPINDEX.fields_by_name['app_refs'].message_type = _APPINDEX_APPREFSENTRY
_APPKEY.fields_by_name['meta'].message_type = _APPKEYMETA
_APPKEYINDEXENTRY.fields_by_name['meta'].message_type = _APPKEYMETA
_APPKEYMANAGERCONFIG.fields_by_name['db_loc'].message_type = _LOCATION
_APPKEYSIGNREQUEST.oneofs_by_name['key_selector'].fields.append(
  _APPKEYSIGNREQUEST.fields_by_name['fingerprint'])
_APPKEYSIGNREQUEST.fields_by_name['fingerprint'].containing_oneof = _APPKEYSIGNREQUEST.oneofs_by_name['key_selector']
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['App'] = _APP
DESCRIPTOR.message_types_by_name['AppIndexEntry'] = _APPINDEXENTRY
DESCRIPTOR.message_types_by_name['AppIndex'] = _APPINDEX
DESCRIPTOR.message_types_by_name['S3Ref'] = _S3REF
DESCRIPTOR.message_types_by_name['AppKeyMeta'] = _APPKEYMETA
DESCRIPTOR.message_types_by_name['AppKey'] = _APPKEY
DESCRIPTOR.message_types_by_name['AppKeyIndexEntry'] = _APPKEYINDEXENTRY
DESCRIPTOR.message_types_by_name['AppKeyManagerConfig'] = _APPKEYMANAGERCONFIG
DESCRIPTOR.message_types_by_name['Links'] = _LINKS
DESCRIPTOR.message_types_by_name['AppKeySignRequest'] = _APPKEYSIGNREQUEST
DESCRIPTOR.message_types_by_name['AppKeySignedData'] = _APPKEYSIGNEDDATA

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.Location)
  ))
_sym_db.RegisterMessage(Location)

App = _reflection.GeneratedProtocolMessageType('App', (_message.Message,), dict(

  KeysEntry = _reflection.GeneratedProtocolMessageType('KeysEntry', (_message.Message,), dict(
    DESCRIPTOR = _APP_KEYSENTRY,
    __module__ = 'appkey_pb2'
    # @@protoc_insertion_point(class_scope:appkey.App.KeysEntry)
    ))
  ,
  DESCRIPTOR = _APP,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.App)
  ))
_sym_db.RegisterMessage(App)
_sym_db.RegisterMessage(App.KeysEntry)

AppIndexEntry = _reflection.GeneratedProtocolMessageType('AppIndexEntry', (_message.Message,), dict(
  DESCRIPTOR = _APPINDEXENTRY,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppIndexEntry)
  ))
_sym_db.RegisterMessage(AppIndexEntry)

AppIndex = _reflection.GeneratedProtocolMessageType('AppIndex', (_message.Message,), dict(

  AppRefsEntry = _reflection.GeneratedProtocolMessageType('AppRefsEntry', (_message.Message,), dict(
    DESCRIPTOR = _APPINDEX_APPREFSENTRY,
    __module__ = 'appkey_pb2'
    # @@protoc_insertion_point(class_scope:appkey.AppIndex.AppRefsEntry)
    ))
  ,
  DESCRIPTOR = _APPINDEX,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppIndex)
  ))
_sym_db.RegisterMessage(AppIndex)
_sym_db.RegisterMessage(AppIndex.AppRefsEntry)

S3Ref = _reflection.GeneratedProtocolMessageType('S3Ref', (_message.Message,), dict(
  DESCRIPTOR = _S3REF,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.S3Ref)
  ))
_sym_db.RegisterMessage(S3Ref)

AppKeyMeta = _reflection.GeneratedProtocolMessageType('AppKeyMeta', (_message.Message,), dict(
  DESCRIPTOR = _APPKEYMETA,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKeyMeta)
  ))
_sym_db.RegisterMessage(AppKeyMeta)

AppKey = _reflection.GeneratedProtocolMessageType('AppKey', (_message.Message,), dict(
  DESCRIPTOR = _APPKEY,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKey)
  ))
_sym_db.RegisterMessage(AppKey)

AppKeyIndexEntry = _reflection.GeneratedProtocolMessageType('AppKeyIndexEntry', (_message.Message,), dict(
  DESCRIPTOR = _APPKEYINDEXENTRY,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKeyIndexEntry)
  ))
_sym_db.RegisterMessage(AppKeyIndexEntry)

AppKeyManagerConfig = _reflection.GeneratedProtocolMessageType('AppKeyManagerConfig', (_message.Message,), dict(
  DESCRIPTOR = _APPKEYMANAGERCONFIG,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKeyManagerConfig)
  ))
_sym_db.RegisterMessage(AppKeyManagerConfig)

Links = _reflection.GeneratedProtocolMessageType('Links', (_message.Message,), dict(
  DESCRIPTOR = _LINKS,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.Links)
  ))
_sym_db.RegisterMessage(Links)

AppKeySignRequest = _reflection.GeneratedProtocolMessageType('AppKeySignRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPKEYSIGNREQUEST,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKeySignRequest)
  ))
_sym_db.RegisterMessage(AppKeySignRequest)

AppKeySignedData = _reflection.GeneratedProtocolMessageType('AppKeySignedData', (_message.Message,), dict(
  DESCRIPTOR = _APPKEYSIGNEDDATA,
  __module__ = 'appkey_pb2'
  # @@protoc_insertion_point(class_scope:appkey.AppKeySignedData)
  ))
_sym_db.RegisterMessage(AppKeySignedData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\010appkeypb'))
_APP_KEYSENTRY.has_options = True
_APP_KEYSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_APPINDEX_APPREFSENTRY.has_options = True
_APPINDEX_APPREFSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
