// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appkey.proto

package appkeypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	// Types that are valid to be assigned to Location:
	//	*Location_S3
	//	*Location_Url
	Location             isLocation_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

type isLocation_Location interface {
	isLocation_Location()
}

type Location_S3 struct {
	S3 *S3Ref `protobuf:"bytes,1,opt,name=s3,proto3,oneof"`
}

type Location_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*Location_S3) isLocation_Location() {}

func (*Location_Url) isLocation_Location() {}

func (m *Location) GetLocation() isLocation_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Location) GetS3() *S3Ref {
	if x, ok := m.GetLocation().(*Location_S3); ok {
		return x.S3
	}
	return nil
}

func (m *Location) GetUrl() string {
	if x, ok := m.GetLocation().(*Location_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Location) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Location_OneofMarshaler, _Location_OneofUnmarshaler, _Location_OneofSizer, []interface{}{
		(*Location_S3)(nil),
		(*Location_Url)(nil),
	}
}

func _Location_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Location)
	// location
	switch x := m.Location.(type) {
	case *Location_S3:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.S3); err != nil {
			return err
		}
	case *Location_Url:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Url)
	case nil:
	default:
		return fmt.Errorf("Location.Location has unexpected type %T", x)
	}
	return nil
}

func _Location_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Location)
	switch tag {
	case 1: // location.s3
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(S3Ref)
		err := b.DecodeMessage(msg)
		m.Location = &Location_S3{msg}
		return true, err
	case 2: // location.url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &Location_Url{x}
		return true, err
	default:
		return false, nil
	}
}

func _Location_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Location)
	// location
	switch x := m.Location.(type) {
	case *Location_S3:
		s := proto.Size(x.S3)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Location_Url:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Url)))
		n += len(x.Url)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type App struct {
	Id                   uint64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keys                 map[string]*AppKeyIndexEntry `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{1}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *App) GetKeys() map[string]*AppKeyIndexEntry {
	if m != nil {
		return m.Keys
	}
	return nil
}

type AppIndexEntry struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppIndexEntry) Reset()         { *m = AppIndexEntry{} }
func (m *AppIndexEntry) String() string { return proto.CompactTextString(m) }
func (*AppIndexEntry) ProtoMessage()    {}
func (*AppIndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{2}
}
func (m *AppIndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppIndexEntry.Unmarshal(m, b)
}
func (m *AppIndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppIndexEntry.Marshal(b, m, deterministic)
}
func (dst *AppIndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppIndexEntry.Merge(dst, src)
}
func (m *AppIndexEntry) XXX_Size() int {
	return xxx_messageInfo_AppIndexEntry.Size(m)
}
func (m *AppIndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AppIndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AppIndexEntry proto.InternalMessageInfo

func (m *AppIndexEntry) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AppIndex struct {
	AppRefs              map[uint64]*AppIndexEntry `protobuf:"bytes,1,rep,name=app_refs,json=appRefs,proto3" json:"app_refs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AppIndex) Reset()         { *m = AppIndex{} }
func (m *AppIndex) String() string { return proto.CompactTextString(m) }
func (*AppIndex) ProtoMessage()    {}
func (*AppIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{3}
}
func (m *AppIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppIndex.Unmarshal(m, b)
}
func (m *AppIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppIndex.Marshal(b, m, deterministic)
}
func (dst *AppIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppIndex.Merge(dst, src)
}
func (m *AppIndex) XXX_Size() int {
	return xxx_messageInfo_AppIndex.Size(m)
}
func (m *AppIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_AppIndex.DiscardUnknown(m)
}

var xxx_messageInfo_AppIndex proto.InternalMessageInfo

func (m *AppIndex) GetAppRefs() map[uint64]*AppIndexEntry {
	if m != nil {
		return m.AppRefs
	}
	return nil
}

type S3Ref struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Ref) Reset()         { *m = S3Ref{} }
func (m *S3Ref) String() string { return proto.CompactTextString(m) }
func (*S3Ref) ProtoMessage()    {}
func (*S3Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{4}
}
func (m *S3Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Ref.Unmarshal(m, b)
}
func (m *S3Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Ref.Marshal(b, m, deterministic)
}
func (dst *S3Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Ref.Merge(dst, src)
}
func (m *S3Ref) XXX_Size() int {
	return xxx_messageInfo_S3Ref.Size(m)
}
func (m *S3Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Ref.DiscardUnknown(m)
}

var xxx_messageInfo_S3Ref proto.InternalMessageInfo

func (m *S3Ref) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *S3Ref) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *S3Ref) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type AppKeyMeta struct {
	Fingerprint          string   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	App                  uint64   `protobuf:"varint,2,opt,name=app,proto3" json:"app,omitempty"`
	Disabled             bool     `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	NotBefore            string   `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NoatAfter            string   `protobuf:"bytes,5,opt,name=noat_after,json=noatAfter,proto3" json:"noat_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppKeyMeta) Reset()         { *m = AppKeyMeta{} }
func (m *AppKeyMeta) String() string { return proto.CompactTextString(m) }
func (*AppKeyMeta) ProtoMessage()    {}
func (*AppKeyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{5}
}
func (m *AppKeyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppKeyMeta.Unmarshal(m, b)
}
func (m *AppKeyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppKeyMeta.Marshal(b, m, deterministic)
}
func (dst *AppKeyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppKeyMeta.Merge(dst, src)
}
func (m *AppKeyMeta) XXX_Size() int {
	return xxx_messageInfo_AppKeyMeta.Size(m)
}
func (m *AppKeyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AppKeyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AppKeyMeta proto.InternalMessageInfo

func (m *AppKeyMeta) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AppKeyMeta) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *AppKeyMeta) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *AppKeyMeta) GetNotBefore() string {
	if m != nil {
		return m.NotBefore
	}
	return ""
}

func (m *AppKeyMeta) GetNoatAfter() string {
	if m != nil {
		return m.NoatAfter
	}
	return ""
}

type AppKey struct {
	Meta                 *AppKeyMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Key                  []byte      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppKey) Reset()         { *m = AppKey{} }
func (m *AppKey) String() string { return proto.CompactTextString(m) }
func (*AppKey) ProtoMessage()    {}
func (*AppKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{6}
}
func (m *AppKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppKey.Unmarshal(m, b)
}
func (m *AppKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppKey.Marshal(b, m, deterministic)
}
func (dst *AppKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppKey.Merge(dst, src)
}
func (m *AppKey) XXX_Size() int {
	return xxx_messageInfo_AppKey.Size(m)
}
func (m *AppKey) XXX_DiscardUnknown() {
	xxx_messageInfo_AppKey.DiscardUnknown(m)
}

var xxx_messageInfo_AppKey proto.InternalMessageInfo

func (m *AppKey) GetMeta() *AppKeyMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *AppKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type AppKeyIndexEntry struct {
	Meta                 *AppKeyMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppKeyIndexEntry) Reset()         { *m = AppKeyIndexEntry{} }
func (m *AppKeyIndexEntry) String() string { return proto.CompactTextString(m) }
func (*AppKeyIndexEntry) ProtoMessage()    {}
func (*AppKeyIndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{7}
}
func (m *AppKeyIndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppKeyIndexEntry.Unmarshal(m, b)
}
func (m *AppKeyIndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppKeyIndexEntry.Marshal(b, m, deterministic)
}
func (dst *AppKeyIndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppKeyIndexEntry.Merge(dst, src)
}
func (m *AppKeyIndexEntry) XXX_Size() int {
	return xxx_messageInfo_AppKeyIndexEntry.Size(m)
}
func (m *AppKeyIndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AppKeyIndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AppKeyIndexEntry proto.InternalMessageInfo

func (m *AppKeyIndexEntry) GetMeta() *AppKeyMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AppKeyManagerConfig struct {
	DbLoc                *Location `protobuf:"bytes,1,opt,name=db_loc,json=dbLoc,proto3" json:"db_loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AppKeyManagerConfig) Reset()         { *m = AppKeyManagerConfig{} }
func (m *AppKeyManagerConfig) String() string { return proto.CompactTextString(m) }
func (*AppKeyManagerConfig) ProtoMessage()    {}
func (*AppKeyManagerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{8}
}
func (m *AppKeyManagerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppKeyManagerConfig.Unmarshal(m, b)
}
func (m *AppKeyManagerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppKeyManagerConfig.Marshal(b, m, deterministic)
}
func (dst *AppKeyManagerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppKeyManagerConfig.Merge(dst, src)
}
func (m *AppKeyManagerConfig) XXX_Size() int {
	return xxx_messageInfo_AppKeyManagerConfig.Size(m)
}
func (m *AppKeyManagerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppKeyManagerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppKeyManagerConfig proto.InternalMessageInfo

func (m *AppKeyManagerConfig) GetDbLoc() *Location {
	if m != nil {
		return m.DbLoc
	}
	return nil
}

type Links struct {
	AppIndex             string   `protobuf:"bytes,1,opt,name=app_index,json=appIndex,proto3" json:"app_index,omitempty"`
	App                  string   `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	KeyMeta              string   `protobuf:"bytes,4,opt,name=key_meta,json=keyMeta,proto3" json:"key_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Links) Reset()         { *m = Links{} }
func (m *Links) String() string { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()    {}
func (*Links) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{9}
}
func (m *Links) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Links.Unmarshal(m, b)
}
func (m *Links) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Links.Marshal(b, m, deterministic)
}
func (dst *Links) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Links.Merge(dst, src)
}
func (m *Links) XXX_Size() int {
	return xxx_messageInfo_Links.Size(m)
}
func (m *Links) XXX_DiscardUnknown() {
	xxx_messageInfo_Links.DiscardUnknown(m)
}

var xxx_messageInfo_Links proto.InternalMessageInfo

func (m *Links) GetAppIndex() string {
	if m != nil {
		return m.AppIndex
	}
	return ""
}

func (m *Links) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Links) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Links) GetKeyMeta() string {
	if m != nil {
		return m.KeyMeta
	}
	return ""
}

type AddAppRequest struct {
	App                  uint64    `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Keys                 []*AppKey `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddAppRequest) Reset()         { *m = AddAppRequest{} }
func (m *AddAppRequest) String() string { return proto.CompactTextString(m) }
func (*AddAppRequest) ProtoMessage()    {}
func (*AddAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{10}
}
func (m *AddAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAppRequest.Unmarshal(m, b)
}
func (m *AddAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAppRequest.Marshal(b, m, deterministic)
}
func (dst *AddAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAppRequest.Merge(dst, src)
}
func (m *AddAppRequest) XXX_Size() int {
	return xxx_messageInfo_AddAppRequest.Size(m)
}
func (m *AddAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAppRequest proto.InternalMessageInfo

func (m *AddAppRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *AddAppRequest) GetKeys() []*AppKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type AddAppResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAppResponse) Reset()         { *m = AddAppResponse{} }
func (m *AddAppResponse) String() string { return proto.CompactTextString(m) }
func (*AddAppResponse) ProtoMessage()    {}
func (*AddAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{11}
}
func (m *AddAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAppResponse.Unmarshal(m, b)
}
func (m *AddAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAppResponse.Marshal(b, m, deterministic)
}
func (dst *AddAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAppResponse.Merge(dst, src)
}
func (m *AddAppResponse) XXX_Size() int {
	return xxx_messageInfo_AddAppResponse.Size(m)
}
func (m *AddAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAppResponse proto.InternalMessageInfo

type RemoveAppRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAppRequest) Reset()         { *m = RemoveAppRequest{} }
func (m *RemoveAppRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAppRequest) ProtoMessage()    {}
func (*RemoveAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{12}
}
func (m *RemoveAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAppRequest.Unmarshal(m, b)
}
func (m *RemoveAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAppRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAppRequest.Merge(dst, src)
}
func (m *RemoveAppRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAppRequest.Size(m)
}
func (m *RemoveAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAppRequest proto.InternalMessageInfo

func (m *RemoveAppRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type RemoveAppResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAppResponse) Reset()         { *m = RemoveAppResponse{} }
func (m *RemoveAppResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveAppResponse) ProtoMessage()    {}
func (*RemoveAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{13}
}
func (m *RemoveAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAppResponse.Unmarshal(m, b)
}
func (m *RemoveAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAppResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAppResponse.Merge(dst, src)
}
func (m *RemoveAppResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveAppResponse.Size(m)
}
func (m *RemoveAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAppResponse proto.InternalMessageInfo

type GetAppRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppRequest) Reset()         { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()    {}
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{14}
}
func (m *GetAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequest.Unmarshal(m, b)
}
func (m *GetAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequest.Marshal(b, m, deterministic)
}
func (dst *GetAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequest.Merge(dst, src)
}
func (m *GetAppRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppRequest.Size(m)
}
func (m *GetAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequest proto.InternalMessageInfo

func (m *GetAppRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type ListAppsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsRequest) Reset()         { *m = ListAppsRequest{} }
func (m *ListAppsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppsRequest) ProtoMessage()    {}
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{15}
}
func (m *ListAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsRequest.Unmarshal(m, b)
}
func (m *ListAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsRequest.Marshal(b, m, deterministic)
}
func (dst *ListAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsRequest.Merge(dst, src)
}
func (m *ListAppsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppsRequest.Size(m)
}
func (m *ListAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsRequest proto.InternalMessageInfo

type AddKeyRequest struct {
	App                  uint64    `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Keys                 []*AppKey `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddKeyRequest) Reset()         { *m = AddKeyRequest{} }
func (m *AddKeyRequest) String() string { return proto.CompactTextString(m) }
func (*AddKeyRequest) ProtoMessage()    {}
func (*AddKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{16}
}
func (m *AddKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddKeyRequest.Unmarshal(m, b)
}
func (m *AddKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddKeyRequest.Marshal(b, m, deterministic)
}
func (dst *AddKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddKeyRequest.Merge(dst, src)
}
func (m *AddKeyRequest) XXX_Size() int {
	return xxx_messageInfo_AddKeyRequest.Size(m)
}
func (m *AddKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddKeyRequest proto.InternalMessageInfo

func (m *AddKeyRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *AddKeyRequest) GetKeys() []*AppKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type AddKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddKeyResponse) Reset()         { *m = AddKeyResponse{} }
func (m *AddKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AddKeyResponse) ProtoMessage()    {}
func (*AddKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{17}
}
func (m *AddKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddKeyResponse.Unmarshal(m, b)
}
func (m *AddKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddKeyResponse.Marshal(b, m, deterministic)
}
func (dst *AddKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddKeyResponse.Merge(dst, src)
}
func (m *AddKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AddKeyResponse.Size(m)
}
func (m *AddKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddKeyResponse proto.InternalMessageInfo

type RemoveKeyRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Fingerprints         []string `protobuf:"bytes,2,rep,name=fingerprints,proto3" json:"fingerprints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveKeyRequest) Reset()         { *m = RemoveKeyRequest{} }
func (m *RemoveKeyRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveKeyRequest) ProtoMessage()    {}
func (*RemoveKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{18}
}
func (m *RemoveKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveKeyRequest.Unmarshal(m, b)
}
func (m *RemoveKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveKeyRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveKeyRequest.Merge(dst, src)
}
func (m *RemoveKeyRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveKeyRequest.Size(m)
}
func (m *RemoveKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveKeyRequest proto.InternalMessageInfo

func (m *RemoveKeyRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *RemoveKeyRequest) GetFingerprints() []string {
	if m != nil {
		return m.Fingerprints
	}
	return nil
}

type RemoveKeyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveKeyResponse) Reset()         { *m = RemoveKeyResponse{} }
func (m *RemoveKeyResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveKeyResponse) ProtoMessage()    {}
func (*RemoveKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{19}
}
func (m *RemoveKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveKeyResponse.Unmarshal(m, b)
}
func (m *RemoveKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveKeyResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveKeyResponse.Merge(dst, src)
}
func (m *RemoveKeyResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveKeyResponse.Size(m)
}
func (m *RemoveKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveKeyResponse proto.InternalMessageInfo

type SignRequest struct {
	App           uint64 `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	ProtectedData []byte `protobuf:"bytes,2,opt,name=protected_data,json=protectedData,proto3" json:"protected_data,omitempty"`
	Algorithm     string `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Types that are valid to be assigned to KeySelector:
	//	*SignRequest_Fingerprint
	KeySelector          isSignRequest_KeySelector `protobuf_oneof:"key_selector"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{20}
}
func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (dst *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(dst, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *SignRequest) GetProtectedData() []byte {
	if m != nil {
		return m.ProtectedData
	}
	return nil
}

func (m *SignRequest) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

type isSignRequest_KeySelector interface {
	isSignRequest_KeySelector()
}

type SignRequest_Fingerprint struct {
	Fingerprint string `protobuf:"bytes,4,opt,name=fingerprint,proto3,oneof"`
}

func (*SignRequest_Fingerprint) isSignRequest_KeySelector() {}

func (m *SignRequest) GetKeySelector() isSignRequest_KeySelector {
	if m != nil {
		return m.KeySelector
	}
	return nil
}

func (m *SignRequest) GetFingerprint() string {
	if x, ok := m.GetKeySelector().(*SignRequest_Fingerprint); ok {
		return x.Fingerprint
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SignRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SignRequest_OneofMarshaler, _SignRequest_OneofUnmarshaler, _SignRequest_OneofSizer, []interface{}{
		(*SignRequest_Fingerprint)(nil),
	}
}

func _SignRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SignRequest)
	// key_selector
	switch x := m.KeySelector.(type) {
	case *SignRequest_Fingerprint:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Fingerprint)
	case nil:
	default:
		return fmt.Errorf("SignRequest.KeySelector has unexpected type %T", x)
	}
	return nil
}

func _SignRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SignRequest)
	switch tag {
	case 4: // key_selector.fingerprint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.KeySelector = &SignRequest_Fingerprint{x}
		return true, err
	default:
		return false, nil
	}
}

func _SignRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SignRequest)
	// key_selector
	switch x := m.KeySelector.(type) {
	case *SignRequest_Fingerprint:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Fingerprint)))
		n += len(x.Fingerprint)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SignedData struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	SigningFingerprint   string   `protobuf:"bytes,3,opt,name=signing_fingerprint,json=signingFingerprint,proto3" json:"signing_fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedData) Reset()         { *m = SignedData{} }
func (m *SignedData) String() string { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()    {}
func (*SignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{21}
}
func (m *SignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData.Unmarshal(m, b)
}
func (m *SignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData.Marshal(b, m, deterministic)
}
func (dst *SignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData.Merge(dst, src)
}
func (m *SignedData) XXX_Size() int {
	return xxx_messageInfo_SignedData.Size(m)
}
func (m *SignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData proto.InternalMessageInfo

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedData) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *SignedData) GetSigningFingerprint() string {
	if m != nil {
		return m.SigningFingerprint
	}
	return ""
}

type SignJwtRequest struct {
	App                  uint64          `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Claims               *_struct.Struct `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	Algorithm            string          `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignJwtRequest) Reset()         { *m = SignJwtRequest{} }
func (m *SignJwtRequest) String() string { return proto.CompactTextString(m) }
func (*SignJwtRequest) ProtoMessage()    {}
func (*SignJwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{22}
}
func (m *SignJwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignJwtRequest.Unmarshal(m, b)
}
func (m *SignJwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignJwtRequest.Marshal(b, m, deterministic)
}
func (dst *SignJwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignJwtRequest.Merge(dst, src)
}
func (m *SignJwtRequest) XXX_Size() int {
	return xxx_messageInfo_SignJwtRequest.Size(m)
}
func (m *SignJwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignJwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignJwtRequest proto.InternalMessageInfo

func (m *SignJwtRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *SignJwtRequest) GetClaims() *_struct.Struct {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *SignJwtRequest) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

type SignJwtResponse struct {
	Claims               []byte   `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Algorithm            string   `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignJwtResponse) Reset()         { *m = SignJwtResponse{} }
func (m *SignJwtResponse) String() string { return proto.CompactTextString(m) }
func (*SignJwtResponse) ProtoMessage()    {}
func (*SignJwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_appkey_57cbd7a926f3ae58, []int{23}
}
func (m *SignJwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignJwtResponse.Unmarshal(m, b)
}
func (m *SignJwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignJwtResponse.Marshal(b, m, deterministic)
}
func (dst *SignJwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignJwtResponse.Merge(dst, src)
}
func (m *SignJwtResponse) XXX_Size() int {
	return xxx_messageInfo_SignJwtResponse.Size(m)
}
func (m *SignJwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignJwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignJwtResponse proto.InternalMessageInfo

func (m *SignJwtResponse) GetClaims() []byte {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *SignJwtResponse) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignJwtResponse) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func init() {
	proto.RegisterType((*Location)(nil), "appkey.Location")
	proto.RegisterType((*App)(nil), "appkey.App")
	proto.RegisterMapType((map[string]*AppKeyIndexEntry)(nil), "appkey.App.KeysEntry")
	proto.RegisterType((*AppIndexEntry)(nil), "appkey.AppIndexEntry")
	proto.RegisterType((*AppIndex)(nil), "appkey.AppIndex")
	proto.RegisterMapType((map[uint64]*AppIndexEntry)(nil), "appkey.AppIndex.AppRefsEntry")
	proto.RegisterType((*S3Ref)(nil), "appkey.S3Ref")
	proto.RegisterType((*AppKeyMeta)(nil), "appkey.AppKeyMeta")
	proto.RegisterType((*AppKey)(nil), "appkey.AppKey")
	proto.RegisterType((*AppKeyIndexEntry)(nil), "appkey.AppKeyIndexEntry")
	proto.RegisterType((*AppKeyManagerConfig)(nil), "appkey.AppKeyManagerConfig")
	proto.RegisterType((*Links)(nil), "appkey.Links")
	proto.RegisterType((*AddAppRequest)(nil), "appkey.AddAppRequest")
	proto.RegisterType((*AddAppResponse)(nil), "appkey.AddAppResponse")
	proto.RegisterType((*RemoveAppRequest)(nil), "appkey.RemoveAppRequest")
	proto.RegisterType((*RemoveAppResponse)(nil), "appkey.RemoveAppResponse")
	proto.RegisterType((*GetAppRequest)(nil), "appkey.GetAppRequest")
	proto.RegisterType((*ListAppsRequest)(nil), "appkey.ListAppsRequest")
	proto.RegisterType((*AddKeyRequest)(nil), "appkey.AddKeyRequest")
	proto.RegisterType((*AddKeyResponse)(nil), "appkey.AddKeyResponse")
	proto.RegisterType((*RemoveKeyRequest)(nil), "appkey.RemoveKeyRequest")
	proto.RegisterType((*RemoveKeyResponse)(nil), "appkey.RemoveKeyResponse")
	proto.RegisterType((*SignRequest)(nil), "appkey.SignRequest")
	proto.RegisterType((*SignedData)(nil), "appkey.SignedData")
	proto.RegisterType((*SignJwtRequest)(nil), "appkey.SignJwtRequest")
	proto.RegisterType((*SignJwtResponse)(nil), "appkey.SignJwtResponse")
}

func init() { proto.RegisterFile("appkey.proto", fileDescriptor_appkey_57cbd7a926f3ae58) }

var fileDescriptor_appkey_57cbd7a926f3ae58 = []byte{
	// 956 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4b, 0x73, 0xe3, 0x44,
	0x10, 0x5e, 0xc9, 0x8f, 0xd8, 0xed, 0xc7, 0x7a, 0x27, 0xb5, 0x89, 0x23, 0x76, 0x6b, 0xc3, 0x14,
	0x8f, 0x50, 0x50, 0x76, 0x95, 0x43, 0x15, 0x5b, 0x39, 0x50, 0xd8, 0xb0, 0x90, 0x25, 0xe1, 0xb0,
	0xca, 0x09, 0x2e, 0xae, 0xb1, 0x34, 0x16, 0x53, 0x56, 0x24, 0xad, 0x66, 0x1c, 0xf0, 0x81, 0x5f,
	0xc1, 0x01, 0x8a, 0xff, 0xc8, 0x7f, 0xa0, 0xe6, 0x21, 0x69, 0xe4, 0xdd, 0x0d, 0x1c, 0xb8, 0x79,
	0xba, 0x5b, 0x5f, 0x7f, 0xdd, 0xd3, 0x5f, 0x8f, 0xa1, 0x4f, 0xb2, 0x6c, 0x43, 0x77, 0x93, 0x2c,
	0x4f, 0x45, 0x8a, 0xda, 0xfa, 0xe4, 0x3d, 0x89, 0xd2, 0x34, 0x8a, 0xe9, 0x54, 0x59, 0x57, 0xdb,
	0xf5, 0x94, 0x8b, 0x7c, 0x1b, 0x08, 0x1d, 0x85, 0xaf, 0xa0, 0x73, 0x9d, 0x06, 0x44, 0xb0, 0x34,
	0x41, 0xcf, 0xc0, 0xe5, 0xe7, 0x63, 0xe7, 0xd4, 0x39, 0xeb, 0xcd, 0x06, 0x13, 0x03, 0x76, 0x73,
	0xee, 0xd3, 0xf5, 0xe5, 0x03, 0xdf, 0xe5, 0xe7, 0x08, 0x41, 0x63, 0x9b, 0xc7, 0x63, 0xf7, 0xd4,
	0x39, 0xeb, 0x5e, 0x3e, 0xf0, 0xe5, 0x61, 0x01, 0xd0, 0x89, 0x0d, 0x00, 0xfe, 0xdd, 0x81, 0xc6,
	0x3c, 0xcb, 0xd0, 0x10, 0x5c, 0x16, 0x2a, 0xa0, 0xa6, 0xef, 0xb2, 0x10, 0x7d, 0x02, 0xcd, 0x0d,
	0xdd, 0xf1, 0xb1, 0x7b, 0xda, 0x38, 0xeb, 0xcd, 0x1e, 0x17, 0xd0, 0xf3, 0x2c, 0x9b, 0x5c, 0xd1,
	0x1d, 0x7f, 0x91, 0x88, 0x7c, 0xe7, 0xab, 0x10, 0xef, 0x15, 0x74, 0x4b, 0x13, 0x1a, 0x41, 0x63,
	0x43, 0x77, 0x0a, 0xa8, 0xeb, 0xcb, 0x9f, 0x68, 0x02, 0xad, 0x3b, 0x12, 0x6f, 0xa9, 0xe2, 0xd0,
	0x9b, 0x8d, 0x2d, 0xa8, 0x2b, 0xba, 0x7b, 0x99, 0x84, 0xf4, 0x57, 0x8d, 0xa6, 0xc3, 0x2e, 0xdc,
	0xe7, 0x0e, 0x7e, 0x06, 0x83, 0x79, 0x96, 0x55, 0xbe, 0x7d, 0x7a, 0xf8, 0x0f, 0x07, 0x3a, 0x45,
	0x04, 0x7a, 0x0e, 0x1d, 0x92, 0x65, 0xcb, 0x9c, 0xae, 0xf9, 0xd8, 0x51, 0x7c, 0x9f, 0x5a, 0x49,
	0x54, 0x8c, 0xfc, 0xe1, 0xd3, 0xb5, 0xe1, 0x7d, 0x40, 0xf4, 0xc9, 0x7b, 0x05, 0x7d, 0xdb, 0x61,
	0xb3, 0x6f, 0x6a, 0xf6, 0x9f, 0xd6, 0xd9, 0x3f, 0xde, 0x07, 0x7e, 0x83, 0xfa, 0x4b, 0x68, 0xa9,
	0xfe, 0xa3, 0x23, 0x68, 0xaf, 0xb6, 0xc1, 0x86, 0x0a, 0xd3, 0x0c, 0x73, 0x2a, 0x72, 0xb8, 0x55,
	0x87, 0x8e, 0xa0, 0x9d, 0xd3, 0x88, 0xa5, 0xc9, 0xb8, 0xa1, 0x23, 0xf5, 0x09, 0xff, 0xe5, 0x00,
	0xe8, 0x2e, 0xfd, 0x40, 0x05, 0x41, 0xa7, 0xd0, 0x5b, 0xb3, 0x24, 0xa2, 0x79, 0x96, 0xb3, 0xa4,
	0x40, 0xb5, 0x4d, 0x12, 0x9a, 0x64, 0x99, 0x82, 0x6e, 0xfa, 0xf2, 0x27, 0xf2, 0xa0, 0x13, 0x32,
	0x4e, 0x56, 0x31, 0x0d, 0x15, 0x78, 0xc7, 0x2f, 0xcf, 0xe8, 0x29, 0x40, 0x92, 0x8a, 0xe5, 0x8a,
	0xae, 0xd3, 0x9c, 0x8e, 0x9b, 0x0a, 0xae, 0x9b, 0xa4, 0x62, 0xa1, 0x0c, 0xda, 0x4d, 0xc4, 0x92,
	0xac, 0x05, 0xcd, 0xc7, 0xad, 0xc2, 0x4d, 0xc4, 0x5c, 0x1a, 0xf0, 0x02, 0xda, 0x9a, 0x1b, 0xfa,
	0x08, 0x9a, 0xb7, 0x54, 0x10, 0x33, 0x85, 0xa8, 0x7e, 0xbf, 0x92, 0xb9, 0xaf, 0xfc, 0x76, 0xe1,
	0x7d, 0x55, 0x38, 0xbe, 0x80, 0xd1, 0xfe, 0x14, 0xfc, 0x57, 0x34, 0xfc, 0x25, 0x1c, 0x1a, 0x1b,
	0x49, 0x48, 0x44, 0xf3, 0xaf, 0xd3, 0x64, 0xcd, 0x22, 0xf4, 0x31, 0xb4, 0xc3, 0xd5, 0x32, 0x4e,
	0x03, 0x03, 0x30, 0x2a, 0x00, 0x0a, 0xc9, 0xf8, 0xad, 0x70, 0x75, 0x9d, 0x06, 0x38, 0x80, 0xd6,
	0x35, 0x4b, 0x36, 0x1c, 0xbd, 0x07, 0x5d, 0x39, 0x3d, 0x4c, 0x52, 0x30, 0x4d, 0x95, 0xe3, 0xa4,
	0x47, 0xcb, 0xea, 0x68, 0x57, 0x77, 0xd4, 0x54, 0xd1, 0xa8, 0xae, 0xef, 0x04, 0x3a, 0x1b, 0xba,
	0x5b, 0x2a, 0xd6, 0xba, 0x8b, 0x07, 0x1b, 0x4d, 0x15, 0xbf, 0x80, 0xc1, 0x3c, 0x0c, 0xd5, 0x88,
	0xbd, 0xde, 0x52, 0x5e, 0xde, 0x90, 0x53, 0xdd, 0x10, 0xae, 0x09, 0x6d, 0x58, 0xaf, 0x57, 0x2b,
	0x0c, 0x8f, 0x60, 0x58, 0xc0, 0xf0, 0x2c, 0x4d, 0x38, 0xc5, 0x1f, 0xc0, 0xc8, 0xa7, 0xb7, 0xe9,
	0x1d, 0xbd, 0x0f, 0x1b, 0x1f, 0xc2, 0x23, 0x2b, 0xca, 0x7c, 0xfa, 0x3e, 0x0c, 0xbe, 0xa3, 0xe2,
	0xde, 0xef, 0x1e, 0xc1, 0xc3, 0x6b, 0xc6, 0x65, 0x0c, 0x37, 0x41, 0xa6, 0x12, 0x49, 0xe9, 0x7f,
	0xa8, 0x44, 0xc1, 0x18, 0x3a, 0x97, 0x45, 0x25, 0xff, 0x82, 0xdd, 0xb7, 0x06, 0x5d, 0xe7, 0xe8,
	0xfa, 0x35, 0x5b, 0x55, 0xad, 0x0d, 0xff, 0xa7, 0x03, 0xbd, 0x1b, 0x16, 0x25, 0xef, 0x86, 0xfe,
	0x10, 0x86, 0x72, 0xaf, 0xd2, 0x40, 0xd0, 0x70, 0x19, 0x12, 0x41, 0xcc, 0x84, 0x0e, 0x4a, 0xeb,
	0x37, 0x44, 0x10, 0xf4, 0x04, 0xba, 0x24, 0x8e, 0xd2, 0x9c, 0x89, 0x9f, 0x6f, 0xcd, 0xed, 0x57,
	0x06, 0x84, 0xeb, 0xda, 0x6c, 0x9a, 0x75, 0x6b, 0x1b, 0x17, 0x43, 0xe8, 0xcb, 0x39, 0xe1, 0x34,
	0xa6, 0x81, 0x48, 0x73, 0xbc, 0x03, 0x90, 0xcc, 0x2a, 0x7c, 0xce, 0xa2, 0x84, 0x88, 0x6d, 0x4e,
	0x15, 0xbd, 0xbe, 0x5f, 0x19, 0xea, 0xd9, 0xdd, 0xfd, 0xec, 0x53, 0x38, 0x94, 0xa1, 0x2c, 0x89,
	0x96, 0x36, 0x0b, 0xcd, 0x12, 0x19, 0xd7, 0xb7, 0x95, 0x07, 0xbf, 0x86, 0xa1, 0x4c, 0xfd, 0xfd,
	0x2f, 0xe2, 0xdd, 0x7d, 0x99, 0x42, 0x3b, 0x88, 0x09, 0xbb, 0xe5, 0x66, 0xf5, 0x1d, 0x4f, 0xf4,
	0xab, 0x34, 0x29, 0x5e, 0xa5, 0xc9, 0x8d, 0x7a, 0x95, 0x7c, 0x13, 0x76, 0x7f, 0x87, 0xf0, 0x8f,
	0xf0, 0xb0, 0x4c, 0xa9, 0xef, 0x46, 0xee, 0x3d, 0x93, 0x41, 0xd7, 0x5b, 0x00, 0x8d, 0xa0, 0xc1,
	0x59, 0x54, 0x2c, 0x0a, 0xce, 0xa2, 0xfb, 0xa1, 0x67, 0x7f, 0xbb, 0xf0, 0xa8, 0x5a, 0x04, 0x37,
	0x34, 0xbf, 0x63, 0x01, 0x45, 0x5f, 0x40, 0x5b, 0x8b, 0x06, 0x55, 0x4b, 0xdb, 0xd6, 0xa2, 0x77,
	0xb4, 0x6f, 0x36, 0xb4, 0xbe, 0x82, 0x6e, 0xa9, 0x1a, 0x54, 0x3e, 0x57, 0xfb, 0x72, 0xf3, 0x4e,
	0xde, 0xe2, 0x31, 0x08, 0x9f, 0x41, 0x5b, 0x4b, 0xac, 0x4a, 0x5d, 0x93, 0x9c, 0xd7, 0xb3, 0xc4,
	0x81, 0x3e, 0x87, 0x03, 0xad, 0x36, 0x8e, 0x8e, 0xcb, 0x6d, 0x55, 0x97, 0x9f, 0x37, 0xda, 0x7f,
	0x77, 0x4c, 0x79, 0x72, 0xff, 0xda, 0xe5, 0x55, 0x22, 0xaa, 0x95, 0x67, 0x29, 0xa2, 0x2a, 0x4f,
	0x7e, 0xbb, 0x57, 0x9e, 0xf5, 0xf9, 0xc9, 0x5b, 0x3c, 0x1a, 0x61, 0xf6, 0x9b, 0x9e, 0x1e, 0x96,
	0x44, 0x45, 0xaf, 0xa7, 0xd0, 0x94, 0x16, 0x74, 0x58, 0xfe, 0x05, 0xa9, 0x24, 0xe7, 0x21, 0xdb,
	0x68, 0xa6, 0xfd, 0x02, 0x0e, 0xcc, 0x34, 0xa0, 0x23, 0xdb, 0x5d, 0x4d, 0xa4, 0x77, 0xfc, 0x86,
	0x5d, 0xa7, 0x5f, 0xc0, 0x4f, 0x1d, 0xed, 0xc9, 0x56, 0xab, 0xb6, 0x1a, 0xc6, 0xf3, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0xb8, 0x71, 0x95, 0x48, 0x09, 0x00, 0x00,
}
