// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package tokenpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type S3Ref struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Ref) Reset()         { *m = S3Ref{} }
func (m *S3Ref) String() string { return proto.CompactTextString(m) }
func (*S3Ref) ProtoMessage()    {}
func (*S3Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{0}
}
func (m *S3Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Ref.Unmarshal(m, b)
}
func (m *S3Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Ref.Marshal(b, m, deterministic)
}
func (dst *S3Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Ref.Merge(dst, src)
}
func (m *S3Ref) XXX_Size() int {
	return xxx_messageInfo_S3Ref.Size(m)
}
func (m *S3Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Ref.DiscardUnknown(m)
}

var xxx_messageInfo_S3Ref proto.InternalMessageInfo

func (m *S3Ref) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *S3Ref) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *S3Ref) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Location struct {
	// Types that are valid to be assigned to Location:
	//	*Location_S3
	//	*Location_Url
	Location             isLocation_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{1}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

type isLocation_Location interface {
	isLocation_Location()
}

type Location_S3 struct {
	S3 *S3Ref `protobuf:"bytes,1,opt,name=s3,proto3,oneof"`
}
type Location_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*Location_S3) isLocation_Location()  {}
func (*Location_Url) isLocation_Location() {}

func (m *Location) GetLocation() isLocation_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Location) GetS3() *S3Ref {
	if x, ok := m.GetLocation().(*Location_S3); ok {
		return x.S3
	}
	return nil
}

func (m *Location) GetUrl() string {
	if x, ok := m.GetLocation().(*Location_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Location) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Location_OneofMarshaler, _Location_OneofUnmarshaler, _Location_OneofSizer, []interface{}{
		(*Location_S3)(nil),
		(*Location_Url)(nil),
	}
}

func _Location_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Location)
	// location
	switch x := m.Location.(type) {
	case *Location_S3:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.S3); err != nil {
			return err
		}
	case *Location_Url:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Url)
	case nil:
	default:
		return fmt.Errorf("Location.Location has unexpected type %T", x)
	}
	return nil
}

func _Location_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Location)
	switch tag {
	case 1: // location.s3
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(S3Ref)
		err := b.DecodeMessage(msg)
		m.Location = &Location_S3{msg}
		return true, err
	case 2: // location.url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Location = &Location_Url{x}
		return true, err
	default:
		return false, nil
	}
}

func _Location_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Location)
	// location
	switch x := m.Location.(type) {
	case *Location_S3:
		s := proto.Size(x.S3)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Location_Url:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Url)))
		n += len(x.Url)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Links struct {
	AppTokens            string   `protobuf:"bytes,1,opt,name=app_tokens,json=appTokens,proto3" json:"app_tokens,omitempty"`
	InstallTokens        string   `protobuf:"bytes,2,opt,name=install_tokens,json=installTokens,proto3" json:"install_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Links) Reset()         { *m = Links{} }
func (m *Links) String() string { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()    {}
func (*Links) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{2}
}
func (m *Links) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Links.Unmarshal(m, b)
}
func (m *Links) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Links.Marshal(b, m, deterministic)
}
func (dst *Links) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Links.Merge(dst, src)
}
func (m *Links) XXX_Size() int {
	return xxx_messageInfo_Links.Size(m)
}
func (m *Links) XXX_DiscardUnknown() {
	xxx_messageInfo_Links.DiscardUnknown(m)
}

var xxx_messageInfo_Links proto.InternalMessageInfo

func (m *Links) GetAppTokens() string {
	if m != nil {
		return m.AppTokens
	}
	return ""
}

func (m *Links) GetInstallTokens() string {
	if m != nil {
		return m.InstallTokens
	}
	return ""
}

type AppToken struct {
	App                  uint64               `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Token                []byte               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppToken) Reset()         { *m = AppToken{} }
func (m *AppToken) String() string { return proto.CompactTextString(m) }
func (*AppToken) ProtoMessage()    {}
func (*AppToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{3}
}
func (m *AppToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppToken.Unmarshal(m, b)
}
func (m *AppToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppToken.Marshal(b, m, deterministic)
}
func (dst *AppToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppToken.Merge(dst, src)
}
func (m *AppToken) XXX_Size() int {
	return xxx_messageInfo_AppToken.Size(m)
}
func (m *AppToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AppToken.DiscardUnknown(m)
}

var xxx_messageInfo_AppToken proto.InternalMessageInfo

func (m *AppToken) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *AppToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AppToken) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type InstallToken struct {
	App                  uint64               `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Install              uint64               `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	Token                []byte               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstallToken) Reset()         { *m = InstallToken{} }
func (m *InstallToken) String() string { return proto.CompactTextString(m) }
func (*InstallToken) ProtoMessage()    {}
func (*InstallToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{4}
}
func (m *InstallToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallToken.Unmarshal(m, b)
}
func (m *InstallToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallToken.Marshal(b, m, deterministic)
}
func (dst *InstallToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallToken.Merge(dst, src)
}
func (m *InstallToken) XXX_Size() int {
	return xxx_messageInfo_InstallToken.Size(m)
}
func (m *InstallToken) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallToken.DiscardUnknown(m)
}

var xxx_messageInfo_InstallToken proto.InternalMessageInfo

func (m *InstallToken) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *InstallToken) GetInstall() uint64 {
	if m != nil {
		return m.Install
	}
	return 0
}

func (m *InstallToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *InstallToken) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type GetAppTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppTokenRequest) Reset()         { *m = GetAppTokenRequest{} }
func (m *GetAppTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppTokenRequest) ProtoMessage()    {}
func (*GetAppTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{5}
}
func (m *GetAppTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppTokenRequest.Unmarshal(m, b)
}
func (m *GetAppTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetAppTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppTokenRequest.Merge(dst, src)
}
func (m *GetAppTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppTokenRequest.Size(m)
}
func (m *GetAppTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppTokenRequest proto.InternalMessageInfo

func (m *GetAppTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type GetAppTokenResponse struct {
	Token                *AppToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAppTokenResponse) Reset()         { *m = GetAppTokenResponse{} }
func (m *GetAppTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppTokenResponse) ProtoMessage()    {}
func (*GetAppTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{6}
}
func (m *GetAppTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppTokenResponse.Unmarshal(m, b)
}
func (m *GetAppTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetAppTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppTokenResponse.Merge(dst, src)
}
func (m *GetAppTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppTokenResponse.Size(m)
}
func (m *GetAppTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppTokenResponse proto.InternalMessageInfo

func (m *GetAppTokenResponse) GetToken() *AppToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetInstallTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Install              uint64   `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstallTokenRequest) Reset()         { *m = GetInstallTokenRequest{} }
func (m *GetInstallTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstallTokenRequest) ProtoMessage()    {}
func (*GetInstallTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{7}
}
func (m *GetInstallTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallTokenRequest.Unmarshal(m, b)
}
func (m *GetInstallTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetInstallTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallTokenRequest.Merge(dst, src)
}
func (m *GetInstallTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstallTokenRequest.Size(m)
}
func (m *GetInstallTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallTokenRequest proto.InternalMessageInfo

func (m *GetInstallTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *GetInstallTokenRequest) GetInstall() uint64 {
	if m != nil {
		return m.Install
	}
	return 0
}

type GetInstallTokenResponse struct {
	Token                *InstallToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInstallTokenResponse) Reset()         { *m = GetInstallTokenResponse{} }
func (m *GetInstallTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstallTokenResponse) ProtoMessage()    {}
func (*GetInstallTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{8}
}
func (m *GetInstallTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallTokenResponse.Unmarshal(m, b)
}
func (m *GetInstallTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetInstallTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallTokenResponse.Merge(dst, src)
}
func (m *GetInstallTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstallTokenResponse.Size(m)
}
func (m *GetInstallTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallTokenResponse proto.InternalMessageInfo

func (m *GetInstallTokenResponse) GetToken() *InstallToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutAppTokenRequest struct {
	Token                *AppToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutAppTokenRequest) Reset()         { *m = PutAppTokenRequest{} }
func (m *PutAppTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PutAppTokenRequest) ProtoMessage()    {}
func (*PutAppTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{9}
}
func (m *PutAppTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppTokenRequest.Unmarshal(m, b)
}
func (m *PutAppTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppTokenRequest.Marshal(b, m, deterministic)
}
func (dst *PutAppTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppTokenRequest.Merge(dst, src)
}
func (m *PutAppTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PutAppTokenRequest.Size(m)
}
func (m *PutAppTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppTokenRequest proto.InternalMessageInfo

func (m *PutAppTokenRequest) GetToken() *AppToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutAppTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutAppTokenResponse) Reset()         { *m = PutAppTokenResponse{} }
func (m *PutAppTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PutAppTokenResponse) ProtoMessage()    {}
func (*PutAppTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{10}
}
func (m *PutAppTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppTokenResponse.Unmarshal(m, b)
}
func (m *PutAppTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppTokenResponse.Marshal(b, m, deterministic)
}
func (dst *PutAppTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppTokenResponse.Merge(dst, src)
}
func (m *PutAppTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PutAppTokenResponse.Size(m)
}
func (m *PutAppTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppTokenResponse proto.InternalMessageInfo

type PutInstallTokenRequest struct {
	Token                *InstallToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutInstallTokenRequest) Reset()         { *m = PutInstallTokenRequest{} }
func (m *PutInstallTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PutInstallTokenRequest) ProtoMessage()    {}
func (*PutInstallTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{11}
}
func (m *PutInstallTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutInstallTokenRequest.Unmarshal(m, b)
}
func (m *PutInstallTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutInstallTokenRequest.Marshal(b, m, deterministic)
}
func (dst *PutInstallTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutInstallTokenRequest.Merge(dst, src)
}
func (m *PutInstallTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PutInstallTokenRequest.Size(m)
}
func (m *PutInstallTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutInstallTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutInstallTokenRequest proto.InternalMessageInfo

func (m *PutInstallTokenRequest) GetToken() *InstallToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutInstallTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutInstallTokenResponse) Reset()         { *m = PutInstallTokenResponse{} }
func (m *PutInstallTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PutInstallTokenResponse) ProtoMessage()    {}
func (*PutInstallTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{12}
}
func (m *PutInstallTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutInstallTokenResponse.Unmarshal(m, b)
}
func (m *PutInstallTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutInstallTokenResponse.Marshal(b, m, deterministic)
}
func (dst *PutInstallTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutInstallTokenResponse.Merge(dst, src)
}
func (m *PutInstallTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PutInstallTokenResponse.Size(m)
}
func (m *PutInstallTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutInstallTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutInstallTokenResponse proto.InternalMessageInfo

type DeleteAppTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppTokenRequest) Reset()         { *m = DeleteAppTokenRequest{} }
func (m *DeleteAppTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppTokenRequest) ProtoMessage()    {}
func (*DeleteAppTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{13}
}
func (m *DeleteAppTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppTokenRequest.Unmarshal(m, b)
}
func (m *DeleteAppTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppTokenRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAppTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppTokenRequest.Merge(dst, src)
}
func (m *DeleteAppTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppTokenRequest.Size(m)
}
func (m *DeleteAppTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppTokenRequest proto.InternalMessageInfo

func (m *DeleteAppTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type DeleteAppTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppTokenResponse) Reset()         { *m = DeleteAppTokenResponse{} }
func (m *DeleteAppTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAppTokenResponse) ProtoMessage()    {}
func (*DeleteAppTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{14}
}
func (m *DeleteAppTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppTokenResponse.Unmarshal(m, b)
}
func (m *DeleteAppTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppTokenResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteAppTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppTokenResponse.Merge(dst, src)
}
func (m *DeleteAppTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAppTokenResponse.Size(m)
}
func (m *DeleteAppTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppTokenResponse proto.InternalMessageInfo

type DeleteInstallTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Install              uint64   `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInstallTokenRequest) Reset()         { *m = DeleteInstallTokenRequest{} }
func (m *DeleteInstallTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteInstallTokenRequest) ProtoMessage()    {}
func (*DeleteInstallTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{15}
}
func (m *DeleteInstallTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstallTokenRequest.Unmarshal(m, b)
}
func (m *DeleteInstallTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstallTokenRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteInstallTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstallTokenRequest.Merge(dst, src)
}
func (m *DeleteInstallTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteInstallTokenRequest.Size(m)
}
func (m *DeleteInstallTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstallTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstallTokenRequest proto.InternalMessageInfo

func (m *DeleteInstallTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *DeleteInstallTokenRequest) GetInstall() uint64 {
	if m != nil {
		return m.Install
	}
	return 0
}

type DeleteInstallTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInstallTokenResponse) Reset()         { *m = DeleteInstallTokenResponse{} }
func (m *DeleteInstallTokenResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteInstallTokenResponse) ProtoMessage()    {}
func (*DeleteInstallTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_a52e49db3b5285ad, []int{16}
}
func (m *DeleteInstallTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstallTokenResponse.Unmarshal(m, b)
}
func (m *DeleteInstallTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstallTokenResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteInstallTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstallTokenResponse.Merge(dst, src)
}
func (m *DeleteInstallTokenResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteInstallTokenResponse.Size(m)
}
func (m *DeleteInstallTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstallTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstallTokenResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*S3Ref)(nil), "token.S3Ref")
	proto.RegisterType((*Location)(nil), "token.Location")
	proto.RegisterType((*Links)(nil), "token.Links")
	proto.RegisterType((*AppToken)(nil), "token.AppToken")
	proto.RegisterType((*InstallToken)(nil), "token.InstallToken")
	proto.RegisterType((*GetAppTokenRequest)(nil), "token.GetAppTokenRequest")
	proto.RegisterType((*GetAppTokenResponse)(nil), "token.GetAppTokenResponse")
	proto.RegisterType((*GetInstallTokenRequest)(nil), "token.GetInstallTokenRequest")
	proto.RegisterType((*GetInstallTokenResponse)(nil), "token.GetInstallTokenResponse")
	proto.RegisterType((*PutAppTokenRequest)(nil), "token.PutAppTokenRequest")
	proto.RegisterType((*PutAppTokenResponse)(nil), "token.PutAppTokenResponse")
	proto.RegisterType((*PutInstallTokenRequest)(nil), "token.PutInstallTokenRequest")
	proto.RegisterType((*PutInstallTokenResponse)(nil), "token.PutInstallTokenResponse")
	proto.RegisterType((*DeleteAppTokenRequest)(nil), "token.DeleteAppTokenRequest")
	proto.RegisterType((*DeleteAppTokenResponse)(nil), "token.DeleteAppTokenResponse")
	proto.RegisterType((*DeleteInstallTokenRequest)(nil), "token.DeleteInstallTokenRequest")
	proto.RegisterType((*DeleteInstallTokenResponse)(nil), "token.DeleteInstallTokenResponse")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_token_a52e49db3b5285ad) }

var fileDescriptor_token_a52e49db3b5285ad = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0xa5, 0x4e, 0xda, 0x64, 0x92, 0x5f, 0x8b, 0x26, 0x34, 0x75, 0xac, 0xa6, 0x14, 0x4b,
	0x20, 0x7a, 0x71, 0xa5, 0xe4, 0x06, 0x5c, 0x28, 0x91, 0x4a, 0x51, 0x2b, 0x55, 0x4e, 0x2f, 0x70,
	0x41, 0x49, 0xb4, 0x8d, 0xac, 0xb8, 0xb6, 0xf1, 0x1f, 0x04, 0xdf, 0x81, 0xcf, 0xc9, 0xe7, 0x60,
	0xbd, 0x3b, 0x76, 0xed, 0x78, 0x0d, 0x54, 0x88, 0x9b, 0x67, 0xe6, 0xcd, 0x9b, 0x37, 0xf3, 0x56,
	0x86, 0x6e, 0xec, 0xaf, 0x99, 0x67, 0x05, 0xa1, 0x1f, 0xfb, 0xd8, 0x12, 0x81, 0xf1, 0x64, 0xe5,
	0xfb, 0x2b, 0x97, 0x9d, 0x8a, 0xe4, 0x22, 0xb9, 0x3d, 0x8d, 0x9d, 0x3b, 0x16, 0xc5, 0xf3, 0xbb,
	0x40, 0xe2, 0xcc, 0x0b, 0x68, 0xcd, 0x26, 0x36, 0xbb, 0xc5, 0x01, 0x6c, 0x2f, 0x92, 0xe5, 0x9a,
	0xc5, 0x7a, 0xe3, 0xb8, 0xf1, 0xa2, 0x63, 0x53, 0x84, 0x8f, 0x40, 0x5b, 0xb3, 0x6f, 0xfa, 0x96,
	0x48, 0xa6, 0x9f, 0x29, 0x32, 0x64, 0x2b, 0xc7, 0xf7, 0x74, 0x4d, 0x22, 0x65, 0x64, 0xbe, 0x87,
	0xf6, 0xa5, 0xbf, 0x9c, 0xc7, 0xfc, 0x1b, 0x8f, 0x60, 0x2b, 0x9a, 0x08, 0xa6, 0xee, 0xb8, 0x67,
	0x49, 0x61, 0x62, 0xce, 0xbb, 0xff, 0x6c, 0x5e, 0x41, 0x04, 0x2d, 0x09, 0x5d, 0xc9, 0xca, 0x53,
	0x69, 0x70, 0x06, 0xd0, 0x76, 0xa9, 0xdf, 0xbc, 0x82, 0xd6, 0xa5, 0xe3, 0xad, 0x23, 0x1c, 0x01,
	0xcc, 0x83, 0xe0, 0x93, 0x60, 0x88, 0x48, 0x5a, 0x87, 0x67, 0x6e, 0x44, 0x02, 0x9f, 0xc1, 0xae,
	0xe3, 0xf1, 0x7d, 0x5c, 0x37, 0x83, 0x48, 0xa1, 0xff, 0x53, 0x56, 0xc2, 0x4c, 0x0f, 0xda, 0x6f,
	0xa8, 0x27, 0x5d, 0x88, 0xf7, 0x0b, 0xaa, 0xa6, 0x9d, 0x7e, 0xe2, 0x63, 0x90, 0xd7, 0x12, 0xbd,
	0x3d, 0x5b, 0x06, 0xf8, 0x12, 0x80, 0x7d, 0x0d, 0x9c, 0x50, 0x08, 0x12, 0xab, 0x76, 0xc7, 0x86,
	0x25, 0xef, 0x69, 0x65, 0xf7, 0xb4, 0x6e, 0xb2, 0x7b, 0xda, 0x05, 0xb4, 0xf9, 0xbd, 0x01, 0xbd,
	0x8b, 0x82, 0x02, 0xc5, 0x50, 0x1d, 0x76, 0x48, 0xa3, 0x18, 0xdb, 0xb4, 0xb3, 0xf0, 0x5e, 0x8e,
	0x56, 0x2f, 0xa7, 0xf9, 0x20, 0x39, 0xcf, 0x01, 0xcf, 0x59, 0x9c, 0x5d, 0xc0, 0x66, 0x9f, 0x13,
	0x0e, 0xaa, 0x6a, 0x32, 0x5f, 0x43, 0xbf, 0x84, 0x8b, 0x02, 0xdf, 0x8b, 0x18, 0x3f, 0x32, 0x09,
	0x92, 0x7e, 0xee, 0x91, 0x9f, 0x39, 0x4e, 0x56, 0xcd, 0x29, 0x0c, 0x78, 0x77, 0x71, 0xed, 0xda,
	0x49, 0xf5, 0xdb, 0x73, 0x96, 0x83, 0x0a, 0x0b, 0xe9, 0x38, 0x29, 0xeb, 0xe8, 0x93, 0x8e, 0x12,
	0x96, 0xb4, 0xbc, 0x02, 0xbc, 0x4e, 0x2a, 0x1b, 0xff, 0xe1, 0x22, 0xfb, 0xd0, 0x2f, 0x35, 0xcb,
	0xf1, 0xe6, 0x5b, 0x18, 0xf0, 0xb4, 0x6a, 0xbf, 0x07, 0x08, 0x1b, 0xc2, 0x41, 0x85, 0x84, 0xf8,
	0x4f, 0x60, 0x7f, 0xca, 0x5c, 0x16, 0xb3, 0xdf, 0x1b, 0xa5, 0xc3, 0x60, 0x13, 0x4a, 0x24, 0xe7,
	0x30, 0x94, 0x95, 0xbf, 0xf5, 0xe1, 0x10, 0x0c, 0x15, 0x91, 0x1c, 0x33, 0xfe, 0xa1, 0x01, 0x88,
	0xcc, 0x2c, 0xf6, 0x43, 0x86, 0x53, 0xe8, 0x16, 0x1e, 0x0e, 0x0e, 0xe9, 0x00, 0xd5, 0x47, 0x67,
	0x18, 0xaa, 0x12, 0xf9, 0x7b, 0x0d, 0x7b, 0x1b, 0xd6, 0xe3, 0xe8, 0x1e, 0xae, 0x58, 0xc8, 0x38,
	0xaa, 0x2b, 0x13, 0x23, 0xd7, 0x55, 0x70, 0x32, 0xd7, 0x55, 0x7d, 0x1a, 0xb9, 0x2e, 0x85, 0xf1,
	0xa9, 0xae, 0x0d, 0xcf, 0x72, 0x5d, 0xea, 0x07, 0x91, 0xeb, 0xaa, 0xb1, 0x1a, 0xaf, 0x60, 0xb7,
	0xec, 0x1f, 0x1e, 0x52, 0x87, 0xf2, 0x05, 0x18, 0xa3, 0x9a, 0x2a, 0xd1, 0x7d, 0x00, 0xac, 0x7a,
	0x85, 0xc7, 0xa5, 0x26, 0x95, 0xcc, 0xa7, 0xbf, 0x40, 0x90, 0xd1, 0x2b, 0xe8, 0x17, 0xf3, 0x33,
	0x16, 0x7e, 0x71, 0x96, 0xff, 0xc0, 0xaa, 0xb3, 0xce, 0xc7, 0x1d, 0x01, 0x08, 0x16, 0x8b, 0x6d,
	0xf1, 0x3b, 0x9b, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x28, 0x48, 0x98, 0x90, 0xd1, 0x06, 0x00,
	0x00,
}
