// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package tokenpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Links struct {
	AppTokens            string   `protobuf:"bytes,1,opt,name=app_tokens,json=appTokens,proto3" json:"app_tokens,omitempty"`
	InstallTokens        string   `protobuf:"bytes,2,opt,name=install_tokens,json=installTokens,proto3" json:"install_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Links) Reset()         { *m = Links{} }
func (m *Links) String() string { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()    {}
func (*Links) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{0}
}
func (m *Links) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Links.Unmarshal(m, b)
}
func (m *Links) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Links.Marshal(b, m, deterministic)
}
func (dst *Links) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Links.Merge(dst, src)
}
func (m *Links) XXX_Size() int {
	return xxx_messageInfo_Links.Size(m)
}
func (m *Links) XXX_DiscardUnknown() {
	xxx_messageInfo_Links.DiscardUnknown(m)
}

var xxx_messageInfo_Links proto.InternalMessageInfo

func (m *Links) GetAppTokens() string {
	if m != nil {
		return m.AppTokens
	}
	return ""
}

func (m *Links) GetInstallTokens() string {
	if m != nil {
		return m.InstallTokens
	}
	return ""
}

type AppToken struct {
	App                  uint64               `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Token                []byte               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppToken) Reset()         { *m = AppToken{} }
func (m *AppToken) String() string { return proto.CompactTextString(m) }
func (*AppToken) ProtoMessage()    {}
func (*AppToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{1}
}
func (m *AppToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppToken.Unmarshal(m, b)
}
func (m *AppToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppToken.Marshal(b, m, deterministic)
}
func (dst *AppToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppToken.Merge(dst, src)
}
func (m *AppToken) XXX_Size() int {
	return xxx_messageInfo_AppToken.Size(m)
}
func (m *AppToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AppToken.DiscardUnknown(m)
}

var xxx_messageInfo_AppToken proto.InternalMessageInfo

func (m *AppToken) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *AppToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AppToken) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type InstallToken struct {
	App                  uint64               `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Install              uint64               `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	Token                []byte               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstallToken) Reset()         { *m = InstallToken{} }
func (m *InstallToken) String() string { return proto.CompactTextString(m) }
func (*InstallToken) ProtoMessage()    {}
func (*InstallToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{2}
}
func (m *InstallToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallToken.Unmarshal(m, b)
}
func (m *InstallToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallToken.Marshal(b, m, deterministic)
}
func (dst *InstallToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallToken.Merge(dst, src)
}
func (m *InstallToken) XXX_Size() int {
	return xxx_messageInfo_InstallToken.Size(m)
}
func (m *InstallToken) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallToken.DiscardUnknown(m)
}

var xxx_messageInfo_InstallToken proto.InternalMessageInfo

func (m *InstallToken) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *InstallToken) GetInstall() uint64 {
	if m != nil {
		return m.Install
	}
	return 0
}

func (m *InstallToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *InstallToken) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type GetAppTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppTokenRequest) Reset()         { *m = GetAppTokenRequest{} }
func (m *GetAppTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppTokenRequest) ProtoMessage()    {}
func (*GetAppTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{3}
}
func (m *GetAppTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppTokenRequest.Unmarshal(m, b)
}
func (m *GetAppTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetAppTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppTokenRequest.Merge(dst, src)
}
func (m *GetAppTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppTokenRequest.Size(m)
}
func (m *GetAppTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppTokenRequest proto.InternalMessageInfo

func (m *GetAppTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type GetAppTokenResponse struct {
	Token                *AppToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAppTokenResponse) Reset()         { *m = GetAppTokenResponse{} }
func (m *GetAppTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppTokenResponse) ProtoMessage()    {}
func (*GetAppTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{4}
}
func (m *GetAppTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppTokenResponse.Unmarshal(m, b)
}
func (m *GetAppTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetAppTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppTokenResponse.Merge(dst, src)
}
func (m *GetAppTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppTokenResponse.Size(m)
}
func (m *GetAppTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppTokenResponse proto.InternalMessageInfo

func (m *GetAppTokenResponse) GetToken() *AppToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetInstallTokenRequest struct {
	App                  uint64   `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	Install              uint64   `protobuf:"varint,2,opt,name=install,proto3" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstallTokenRequest) Reset()         { *m = GetInstallTokenRequest{} }
func (m *GetInstallTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstallTokenRequest) ProtoMessage()    {}
func (*GetInstallTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{5}
}
func (m *GetInstallTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallTokenRequest.Unmarshal(m, b)
}
func (m *GetInstallTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetInstallTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallTokenRequest.Merge(dst, src)
}
func (m *GetInstallTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstallTokenRequest.Size(m)
}
func (m *GetInstallTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallTokenRequest proto.InternalMessageInfo

func (m *GetInstallTokenRequest) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

func (m *GetInstallTokenRequest) GetInstall() uint64 {
	if m != nil {
		return m.Install
	}
	return 0
}

type GetInstallTokenResponse struct {
	Token                *InstallToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInstallTokenResponse) Reset()         { *m = GetInstallTokenResponse{} }
func (m *GetInstallTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstallTokenResponse) ProtoMessage()    {}
func (*GetInstallTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{6}
}
func (m *GetInstallTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstallTokenResponse.Unmarshal(m, b)
}
func (m *GetInstallTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstallTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetInstallTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstallTokenResponse.Merge(dst, src)
}
func (m *GetInstallTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstallTokenResponse.Size(m)
}
func (m *GetInstallTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstallTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstallTokenResponse proto.InternalMessageInfo

func (m *GetInstallTokenResponse) GetToken() *InstallToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutAppTokenRequest struct {
	Token                *AppToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutAppTokenRequest) Reset()         { *m = PutAppTokenRequest{} }
func (m *PutAppTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PutAppTokenRequest) ProtoMessage()    {}
func (*PutAppTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{7}
}
func (m *PutAppTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppTokenRequest.Unmarshal(m, b)
}
func (m *PutAppTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppTokenRequest.Marshal(b, m, deterministic)
}
func (dst *PutAppTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppTokenRequest.Merge(dst, src)
}
func (m *PutAppTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PutAppTokenRequest.Size(m)
}
func (m *PutAppTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppTokenRequest proto.InternalMessageInfo

func (m *PutAppTokenRequest) GetToken() *AppToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutAppTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutAppTokenResponse) Reset()         { *m = PutAppTokenResponse{} }
func (m *PutAppTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PutAppTokenResponse) ProtoMessage()    {}
func (*PutAppTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{8}
}
func (m *PutAppTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutAppTokenResponse.Unmarshal(m, b)
}
func (m *PutAppTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutAppTokenResponse.Marshal(b, m, deterministic)
}
func (dst *PutAppTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutAppTokenResponse.Merge(dst, src)
}
func (m *PutAppTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PutAppTokenResponse.Size(m)
}
func (m *PutAppTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutAppTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutAppTokenResponse proto.InternalMessageInfo

type PutInstallTokenRequest struct {
	Token                *InstallToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutInstallTokenRequest) Reset()         { *m = PutInstallTokenRequest{} }
func (m *PutInstallTokenRequest) String() string { return proto.CompactTextString(m) }
func (*PutInstallTokenRequest) ProtoMessage()    {}
func (*PutInstallTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{9}
}
func (m *PutInstallTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutInstallTokenRequest.Unmarshal(m, b)
}
func (m *PutInstallTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutInstallTokenRequest.Marshal(b, m, deterministic)
}
func (dst *PutInstallTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutInstallTokenRequest.Merge(dst, src)
}
func (m *PutInstallTokenRequest) XXX_Size() int {
	return xxx_messageInfo_PutInstallTokenRequest.Size(m)
}
func (m *PutInstallTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutInstallTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutInstallTokenRequest proto.InternalMessageInfo

func (m *PutInstallTokenRequest) GetToken() *InstallToken {
	if m != nil {
		return m.Token
	}
	return nil
}

type PutInstallTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutInstallTokenResponse) Reset()         { *m = PutInstallTokenResponse{} }
func (m *PutInstallTokenResponse) String() string { return proto.CompactTextString(m) }
func (*PutInstallTokenResponse) ProtoMessage()    {}
func (*PutInstallTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_b963391d94e86664, []int{10}
}
func (m *PutInstallTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutInstallTokenResponse.Unmarshal(m, b)
}
func (m *PutInstallTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutInstallTokenResponse.Marshal(b, m, deterministic)
}
func (dst *PutInstallTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutInstallTokenResponse.Merge(dst, src)
}
func (m *PutInstallTokenResponse) XXX_Size() int {
	return xxx_messageInfo_PutInstallTokenResponse.Size(m)
}
func (m *PutInstallTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutInstallTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutInstallTokenResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Links)(nil), "token.Links")
	proto.RegisterType((*AppToken)(nil), "token.AppToken")
	proto.RegisterType((*InstallToken)(nil), "token.InstallToken")
	proto.RegisterType((*GetAppTokenRequest)(nil), "token.GetAppTokenRequest")
	proto.RegisterType((*GetAppTokenResponse)(nil), "token.GetAppTokenResponse")
	proto.RegisterType((*GetInstallTokenRequest)(nil), "token.GetInstallTokenRequest")
	proto.RegisterType((*GetInstallTokenResponse)(nil), "token.GetInstallTokenResponse")
	proto.RegisterType((*PutAppTokenRequest)(nil), "token.PutAppTokenRequest")
	proto.RegisterType((*PutAppTokenResponse)(nil), "token.PutAppTokenResponse")
	proto.RegisterType((*PutInstallTokenRequest)(nil), "token.PutInstallTokenRequest")
	proto.RegisterType((*PutInstallTokenResponse)(nil), "token.PutInstallTokenResponse")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_token_b963391d94e86664) }

var fileDescriptor_token_b963391d94e86664 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x93, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x49, 0x3f, 0xfe, 0xfd, 0xf7, 0xb6, 0x5a, 0x99, 0x68, 0x3f, 0x02, 0x55, 0x09, 0x28,
	0xba, 0x49, 0xa1, 0xee, 0xd4, 0x8d, 0x5a, 0x10, 0x41, 0xa1, 0xa4, 0x5d, 0xb9, 0x91, 0x56, 0xc6,
	0x12, 0xda, 0x66, 0xc6, 0x64, 0x22, 0x3e, 0x84, 0x8f, 0xe4, 0xc3, 0x39, 0x9d, 0x99, 0xa4, 0x49,
	0x93, 0x80, 0x5d, 0xb8, 0xcb, 0xdc, 0x39, 0xf7, 0xdc, 0xdf, 0x3d, 0x43, 0xa0, 0xc6, 0xc8, 0x1c,
	0xbb, 0x16, 0xf5, 0x08, 0x23, 0xa8, 0x2c, 0x0e, 0xc6, 0xd1, 0x8c, 0x90, 0xd9, 0x02, 0xf7, 0x44,
	0x71, 0x1a, 0xbc, 0xf5, 0x98, 0xb3, 0xc4, 0x3e, 0x9b, 0x2c, 0xa9, 0xd4, 0x99, 0x4f, 0x50, 0x7e,
	0x74, 0xdc, 0xb9, 0x8f, 0xba, 0x00, 0x13, 0x4a, 0x5f, 0x44, 0x9b, 0xdf, 0xd6, 0x8e, 0xb5, 0xb3,
	0xaa, 0x5d, 0xe5, 0x95, 0xb1, 0x28, 0xa0, 0x13, 0xd8, 0x75, 0x5c, 0xde, 0xb8, 0x58, 0x84, 0x92,
	0x82, 0x90, 0xec, 0xa8, 0xaa, 0x94, 0x99, 0x2e, 0xfc, 0xbf, 0x51, 0x3d, 0x68, 0x0f, 0x8a, 0xbc,
	0x5f, 0x58, 0x95, 0xec, 0xd5, 0x27, 0xda, 0x07, 0x89, 0x25, 0x7a, 0xeb, 0xb6, 0x3c, 0xa0, 0x4b,
	0x00, 0xfc, 0x49, 0x1d, 0x6f, 0xc2, 0x1c, 0xe2, 0xb6, 0x8b, 0xfc, 0xaa, 0xd6, 0x37, 0x2c, 0x09,
	0x6e, 0x85, 0xe0, 0xd6, 0x38, 0x04, 0xb7, 0x63, 0x6a, 0xf3, 0x4b, 0x83, 0xfa, 0x43, 0x8c, 0x20,
	0x63, 0x68, 0x1b, 0x2a, 0x8a, 0x51, 0x8c, 0x2d, 0xd9, 0xe1, 0x71, 0x8d, 0x53, 0xcc, 0xc7, 0x29,
	0x6d, 0x85, 0x73, 0x0a, 0xe8, 0x1e, 0xb3, 0x30, 0x01, 0x1b, 0xbf, 0x07, 0x5c, 0x94, 0x66, 0x32,
	0xaf, 0x41, 0x4f, 0xe8, 0x7c, 0x4a, 0x5c, 0x1f, 0xf3, 0x90, 0x15, 0x90, 0x26, 0xa6, 0x36, 0x2c,
	0xf9, 0xa2, 0x91, 0x4e, 0xde, 0x9a, 0x03, 0x68, 0xf2, 0xee, 0xf8, 0xda, 0xb9, 0x93, 0xf2, 0xb7,
	0xe7, 0x2e, 0xad, 0x94, 0x8b, 0xe2, 0x38, 0x4f, 0x72, 0xe8, 0x8a, 0x23, 0xa1, 0x55, 0x2c, 0x57,
	0x80, 0x86, 0x41, 0x6a, 0xe3, 0x5f, 0x2e, 0x72, 0x00, 0x7a, 0xa2, 0x59, 0x8e, 0x37, 0xef, 0xa0,
	0xc9, 0xcb, 0x59, 0xfb, 0x6d, 0x01, 0xd6, 0x81, 0x56, 0xca, 0x44, 0xfa, 0xf7, 0xbf, 0x0b, 0x00,
	0xa2, 0x32, 0x62, 0xc4, 0xc3, 0x68, 0x00, 0xb5, 0xd8, 0x63, 0xa0, 0x8e, 0x32, 0x4d, 0x3f, 0xa4,
	0x61, 0x64, 0x5d, 0xa9, 0xcc, 0x86, 0xd0, 0xd8, 0x88, 0x13, 0x75, 0xd7, 0xf2, 0x8c, 0x65, 0x8c,
	0xc3, 0xbc, 0x6b, 0xe5, 0xc8, 0xb9, 0x62, 0xe9, 0x44, 0x5c, 0xe9, 0xb8, 0x23, 0xae, 0x8c, 0x30,
	0x57, 0x5c, 0x1b, 0x39, 0x44, 0x5c, 0xd9, 0x21, 0x47, 0x5c, 0x79, 0xf1, 0xcd, 0x40, 0x8f, 0xd7,
	0x47, 0xd8, 0xfb, 0x70, 0x5e, 0xff, 0x20, 0x80, 0xdb, 0xea, 0x73, 0x45, 0x08, 0xe8, 0x74, 0xfa,
	0x4f, 0xfc, 0x78, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xac, 0x51, 0xdd, 0xe4, 0x04,
	0x00, 0x00,
}
